const ShopActionTypes = {
    SET_SHOP_DATA: 'SET_SHOP_DATA',
    FETCH_COLLECTION_START: 'FETCH_COLLECTIONI_START',
    FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS'
}

export default ShopActionTypes