const CartActionTypes = {
    TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    SET_ITEM_QUANTITY: 'SET_ITEM_QUANTITY'
}

export default CartActionTypes;